name = "atomy"
main = "worker/index.js"
compatibility_date = "2025-01-01"

[assets]
directory = "./public"
binding = "ASSETS"
run_worker_first = true
html_handling = "none"

[[d1_databases]]
binding = "DB"
database_name = "atomy-db"
database_id = "2d03afb9-ee89-4dc7-a574-8a92118cb324"
